# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/notebook.ui'
#
# Created: Sat Nov  8 21:35:50 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NotebookDialog(object):
    def setupUi(self, NotebookDialog):
        NotebookDialog.setObjectName("NotebookDialog")
        NotebookDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NotebookDialog.resize(361, 310)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NotebookDialog.sizePolicy().hasHeightForWidth())
        NotebookDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/x-office-address-book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NotebookDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(NotebookDialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.icon = QtGui.QLabel(NotebookDialog)
        self.icon.setPixmap(QtGui.QPixmap(":/notebook_small.png"))
        self.icon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.icon.setObjectName("icon")
        self.gridLayout.addWidget(self.icon, 1, 0, 1, 1)
        self.label = QtGui.QLabel(NotebookDialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 2)
        self.backend = QtGui.QLabel(NotebookDialog)
        self.backend.setObjectName("backend")
        self.gridLayout.addWidget(self.backend, 3, 1, 1, 1)
        self.backends = QtGui.QComboBox(NotebookDialog)
        self.backends.setObjectName("backends")
        self.gridLayout.addWidget(self.backends, 3, 2, 1, 1)
        self.name = QtGui.QLabel(NotebookDialog)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 2, 1, 1, 1)
        self.nameEdit = QtGui.QLineEdit(NotebookDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 2, 2, 1, 1)
        self.path = QtGui.QLabel(NotebookDialog)
        self.path.setObjectName("path")
        self.gridLayout.addWidget(self.path, 6, 1, 1, 1)
        self.pathEdit = QtGui.QLineEdit(NotebookDialog)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 6, 2, 1, 1)
        self.url = QtGui.QLabel(NotebookDialog)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 7, 1, 1, 1)
        self.urlEdit = QtGui.QLineEdit(NotebookDialog)
        self.urlEdit.setObjectName("urlEdit")
        self.gridLayout.addWidget(self.urlEdit, 7, 2, 1, 1)
        self.loginEdit = QtGui.QLineEdit(NotebookDialog)
        self.loginEdit.setObjectName("loginEdit")
        self.gridLayout.addWidget(self.loginEdit, 8, 2, 1, 1)
        self.login = QtGui.QLabel(NotebookDialog)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 8, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(NotebookDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 2, 1, 1)
        self.passwd = QtGui.QLabel(NotebookDialog)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 9, 1, 1, 1)
        self.passwdEdit = QtGui.QLineEdit(NotebookDialog)
        self.passwdEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwdEdit.setObjectName("passwdEdit")
        self.gridLayout.addWidget(self.passwdEdit, 9, 2, 1, 1)
        self.desc = QtGui.QLabel(NotebookDialog)
        self.desc.setObjectName("desc")
        self.gridLayout.addWidget(self.desc, 4, 1, 1, 2)
        self.label_2 = QtGui.QLabel(NotebookDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 1)
        self.markups = QtGui.QComboBox(NotebookDialog)
        self.markups.setObjectName("markups")
        self.markups.addItem(QtCore.QString())
        self.markups.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.markups, 5, 2, 1, 1)

        self.retranslateUi(NotebookDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NotebookDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NotebookDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NotebookDialog)

    def retranslateUi(self, NotebookDialog):
        NotebookDialog.setWindowTitle(QtGui.QApplication.translate("NotebookDialog", "Add notebook", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NotebookDialog", "<b>Add new notebook</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.backend.setText(QtGui.QApplication.translate("NotebookDialog", "Backend: ", None, QtGui.QApplication.UnicodeUTF8))
        self.name.setText(QtGui.QApplication.translate("NotebookDialog", "Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.path.setText(QtGui.QApplication.translate("NotebookDialog", "Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.url.setText(QtGui.QApplication.translate("NotebookDialog", "URL: ", None, QtGui.QApplication.UnicodeUTF8))
        self.urlEdit.setText(QtGui.QApplication.translate("NotebookDialog", "http://", None, QtGui.QApplication.UnicodeUTF8))
        self.login.setText(QtGui.QApplication.translate("NotebookDialog", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwd.setText(QtGui.QApplication.translate("NotebookDialog", "Password: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NotebookDialog", "Markup engine", None, QtGui.QApplication.UnicodeUTF8))
        self.markups.setItemText(0, QtGui.QApplication.translate("NotebookDialog", "Wiki", None, QtGui.QApplication.UnicodeUTF8))
        self.markups.setItemText(1, QtGui.QApplication.translate("NotebookDialog", "HTML", None, QtGui.QApplication.UnicodeUTF8))

import notefinder_rc
